# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
workspace 'finalModule'

target 'DicodingCatalogGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for DicodingCatalogGame

  target 'DicodingCatalogGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end